data:
  source:
    - /home/andrew/Desktop/Classes/COSC_552/substrate-ospray-studio/data/apple
    - /home/andrew/Desktop/Classes/COSC_552/substrate-ospray-studio/data/bust
    - /home/andrew/Desktop/Classes/COSC_552/substrate-ospray-studio/data/lightbulb
    - /home/andrew/Desktop/Classes/COSC_552/substrate-ospray-studio/data/table
    - /home/andrew/Desktop/Classes/COSC_552/substrate-ospray-studio/data/tree
    # - C:/Users/andre/OneDrive/Desktop/Classes/COSC 552/substrate-ospray-studio/data/apple
    # - C:/Users/andre/OneDrive/Desktop/Classes/COSC 552/substrate-ospray-studio/data/bust
    # - C:/Users/andre/OneDrive/Desktop/Classes/COSC 552/substrate-ospray-studio/data/lightbulb
    # - C:/Users/andre/OneDrive/Desktop/Classes/COSC 552/substrate-ospray-studio/data/table
    # - C:/Users/andre/OneDrive/Desktop/Classes/COSC 552/substrate-ospray-studio/data/tree

# aws:
#   bucket: substrate-data-andlrutt
#   region: us-east-2
#   managers:
#     "t3.medium": 1

docker:
  port: 8000
  replicas: 1
