data:
  source:
    - /root/data/apple
    - /root/data/bust
    - /root/data/lightbulb
    - /root/data/table
    - /root/data/tree

aws:
  bucket: substrate-data-andlrutt
  region: us-east-2
  managers:
    "t3.medium": 1
